/* biom-ids.js – erzeugt von companion/tools/biom-ids-bauen.mjs, nicht von Hand ändern.
   Biom-IDs, wie Bedrock sie in Data3D speichert. Quelle: minecraft-data 3.117.0, bedrock/1.20.0/biomes.json
   (ohne Nachträge – neuere Biome meldet der Import als unbekannt).
   displayName entspricht der Schreibweise von Chunkbase und der Biom-Liste in regeln.js.
   Klassisches Script: Seite (<script src>), Worker und Node (import "./biom-ids.js") lesen globalThis.BIOM_IDS. */
globalThis.BIOM_IDS = Object.freeze([
  { id:0, name:"ocean", displayName:"Ocean", color:"#000070" },
  { id:1, name:"plains", displayName:"Plains", color:"#8db360" },
  { id:2, name:"desert", displayName:"Desert", color:"#fa9418" },
  { id:3, name:"extreme_hills", displayName:"Windswept Hills", color:"#606060" },
  { id:4, name:"forest", displayName:"Forest", color:"#056621" },
  { id:5, name:"taiga", displayName:"Taiga", color:"#0b6659" },
  { id:6, name:"swampland", displayName:"Swamp", color:"#07f9b2" },
  { id:7, name:"river", displayName:"River", color:"#0000ff" },
  { id:8, name:"hell", displayName:"Nether Wastes", color:"#bf3b3b" },
  { id:9, name:"the_end", displayName:"The End", color:"#8080ff" },
  { id:10, name:"legacy_frozen_ocean", displayName:"Frozen Ocean", color:"#7070d6" },
  { id:11, name:"frozen_river", displayName:"Frozen River", color:"#a0a0ff" },
  { id:12, name:"ice_plains", displayName:"Snowy Plains", color:"#ffffff" },
  { id:13, name:"ice_mountains", displayName:"Snowy Plains", color:"#ffffff" },
  { id:14, name:"mushroom_island", displayName:"Mushroom Fields", color:"#ff00ff" },
  { id:15, name:"mushroom_island_shore", displayName:"Mushroom Fields", color:"#ff00ff" },
  { id:16, name:"beach", displayName:"Beach", color:"#fade55" },
  { id:17, name:"desert_hills", displayName:"Desert", color:"#fa9418" },
  { id:18, name:"forest_hills", displayName:"Forest", color:"#056621" },
  { id:19, name:"taiga_hills", displayName:"Taiga", color:"#0b6659" },
  { id:20, name:"extreme_hills_edge", displayName:"Windswept Hills", color:"#606060" },
  { id:21, name:"jungle", displayName:"Jungle", color:"#537b09" },
  { id:22, name:"jungle_hills", displayName:"Jungle", color:"#537b09" },
  { id:23, name:"jungle_edge", displayName:"Sparse Jungle", color:"#628b17" },
  { id:24, name:"deep_ocean", displayName:"Deep Ocean", color:"#000030" },
  { id:25, name:"stone_beach", displayName:"Stony Shore", color:"#a2a284" },
  { id:26, name:"cold_beach", displayName:"Snowy Beach", color:"#faf0c0" },
  { id:27, name:"birch_forest", displayName:"Birch Forest", color:"#307444" },
  { id:28, name:"birch_forest_hills", displayName:"Birch Forest", color:"#307444" },
  { id:29, name:"roofed_forest", displayName:"Dark Forest", color:"#40511a" },
  { id:30, name:"cold_taiga", displayName:"Snowy Taiga", color:"#31554a" },
  { id:31, name:"cold_taiga_hills", displayName:"Snowy Taiga", color:"#31554a" },
  { id:32, name:"mega_taiga", displayName:"Old Growth Pine Taiga", color:"#596651" },
  { id:33, name:"mega_taiga_hills", displayName:"Old Growth Pine Taiga", color:"#596651" },
  { id:34, name:"extreme_hills_plus_trees", displayName:"Windswept Forest", color:"#22551c" },
  { id:35, name:"savanna", displayName:"Savanna", color:"#bdb25f" },
  { id:36, name:"savanna_plateau", displayName:"Savanna Plateau", color:"#a79d64" },
  { id:37, name:"mesa", displayName:"Badlands", color:"#d94515" },
  { id:38, name:"mesa_plateau_stone", displayName:"Wooded Badlands", color:"#b09765" },
  { id:39, name:"mesa_plateau", displayName:"Badlands", color:"#d94515" },
  { id:40, name:"warm_ocean", displayName:"Warm Ocean", color:"#0000ac" },
  { id:41, name:"deep_warm_ocean", displayName:"Warm Ocean", color:"#0000ac" },
  { id:42, name:"lukewarm_ocean", displayName:"Lukewarm Ocean", color:"#000090" },
  { id:43, name:"deep_lukewarm_ocean", displayName:"Deep Lukewarm Ocean", color:"#000040" },
  { id:44, name:"cold_ocean", displayName:"Cold Ocean", color:"#202070" },
  { id:45, name:"deep_cold_ocean", displayName:"Deep Cold Ocean", color:"#202038" },
  { id:46, name:"frozen_ocean", displayName:"Frozen Ocean", color:"#7070d6" },
  { id:47, name:"deep_frozen_ocean", displayName:"Deep Frozen Ocean", color:"#404090" },
  { id:48, name:"bamboo_jungle", displayName:"Bamboo Jungle", color:"#768e14" },
  { id:49, name:"bamboo_jungle_hills", displayName:"Bamboo Jungle", color:"#768e14" },
  { id:129, name:"sunflower_plains", displayName:"Sunflower Plains", color:"#b5db88" },
  { id:130, name:"desert_mutated", displayName:"Desert", color:"#fa9418" },
  { id:131, name:"extreme_hills_mutated", displayName:"Windswept Gravelly Hills", color:"#888888" },
  { id:132, name:"flower_forest", displayName:"Flower Forest", color:"#2d8e49" },
  { id:133, name:"taiga_mutated", displayName:"Taiga", color:"#0b6659" },
  { id:134, name:"swampland_mutated", displayName:"Swamp", color:"#07f9b2" },
  { id:140, name:"ice_plains_spikes", displayName:"Ice Spikes", color:"#b4dcdc" },
  { id:149, name:"jungle_mutated", displayName:"Jungle", color:"#537b09" },
  { id:151, name:"jungle_edge_mutated", displayName:"Sparse Jungle", color:"#628b17" },
  { id:155, name:"birch_forest_mutated", displayName:"Old Growth Birch Forest", color:"#589c6c" },
  { id:156, name:"birch_forest_hills_mutated", displayName:"Old Growth Birch Forest", color:"#589c6c" },
  { id:157, name:"roofed_forest_mutated", displayName:"Dark Forest", color:"#40511a" },
  { id:158, name:"cold_taiga_mutated", displayName:"Snowy Taiga", color:"#31554a" },
  { id:160, name:"redwood_taiga_mutated", displayName:"Old Growth Spruce Taiga", color:"#818e79" },
  { id:161, name:"redwood_taiga_hills_mutated", displayName:"Old Growth Spruce Taiga", color:"#818e79" },
  { id:162, name:"extreme_hills_plus_trees_mutated", displayName:"Windswept Gravelly Hills", color:"#888888" },
  { id:163, name:"savanna_mutated", displayName:"Windswept Savanna", color:"#e5da87" },
  { id:164, name:"savanna_plateau_mutated", displayName:"Windswept Savanna", color:"#e5da87" },
  { id:165, name:"mesa_bryce", displayName:"Eroded Badlands", color:"#ff6d3d" },
  { id:166, name:"mesa_plateau_stone_mutated", displayName:"Wooded Badlands", color:"#b09765" },
  { id:167, name:"mesa_plateau_mutated", displayName:"Badlands", color:"#d94515" },
  { id:178, name:"soulsand_valley", displayName:"Soul Sand Valley", color:"#5e3830" },
  { id:179, name:"crimson_forest", displayName:"Crimson Forest", color:"#dd0808" },
  { id:180, name:"warped_forest", displayName:"Warped Forest", color:"#49907b" },
  { id:181, name:"basalt_deltas", displayName:"Basalt Deltas", color:"#403636" },
  { id:182, name:"jagged_peaks", displayName:"Jagged Peaks", color:"#e3eced" },
  { id:183, name:"frozen_peaks", displayName:"Frozen Peaks", color:"#eafbfb" },
  { id:184, name:"snowy_slopes", displayName:"Snowy Slopes", color:"#daf1f1" },
  { id:185, name:"grove", displayName:"Grove", color:"#dfece5" },
  { id:186, name:"meadow", displayName:"Meadow", color:"#8ca470" },
  { id:187, name:"lush_caves", displayName:"Lush Caves", color:"#df9634" },
  { id:188, name:"dripstone_caves", displayName:"Dripstone Caves", color:"#c1a58f" },
  { id:189, name:"stony_peaks", displayName:"Stony Peaks", color:"#d1d1d1" },
  { id:190, name:"deep_dark", displayName:"Deep Dark", color:"#1d2b33" },
  { id:191, name:"mangrove_swamp", displayName:"Mangrove Swamp", color:"#4f6b3a" },
].map(Object.freeze));
